postgres_rhel7_repo:  pgdg-redhat-repo-42.0-11.noarch
postgres_packages:
  - postgresql10 
  - postgresql10-server 
  - postgresql10-contrib 
  - postgresql10-libs
postgres_library: "python-psycopg2"
postgres_10_data_dir: /var/lib/pgsql/10/data
postgres_port: 5432