- hosts: app_servers
  gather_facts: false
  become: yes
  roles:
   - app-tier

- hosts: database_servers
  gather_facts: false
  become: yes
  roles:
   - db-tier

- hosts: load_balancers
  gather_facts: false
  become: yes
  roles:
   - loadbalancing-tier