
---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  
  tasks:
    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        #region_name: regionOne
      register: r_os_servers

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group:
          - "{{ item.metadata.group }}"
         #- "{{ item.metadata.deployment_name }}"
      loop: "{{ r_os_servers.openstack_servers }}"

 
    - name: show data site
      debug:
         msg: "ni contoh {{item.public_v4}} {{item.metadata.group}}"
      loop: "{{ r_os_servers.openstack_servers }}"

      

- hosts: all
  tasks:      
    - name: show all app
      debug: 
         msg: "{{item}}"
      with_items:  groups['apps']   

    - debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
       - all   



- name: Deploy Common repos
  hosts: apps:frontends:appdbs
  gather_facts: false
  become: true
  tags:
    - common

  tasks:

    - name: Copy repo file
      copy:
        src: ../files/open_three-tier-app.repo
        dest: /etc/yum.repos.d/open_three-tier-app.repo
       
       
- hosts: apps
  gather_facts: false
  become: yes
  roles:
   - app-tier

- hosts: appdbs
  gather_facts: false
  become: yes
  roles:
   - db-tier

- hosts: frontends
  gather_facts: false
  become: yes
  roles:
   - loadbalancing-tier
    
